### ISSUE TITLE
KA-Lite Videos are pulled into /var/lib/kalite/content/content

### ISSUE THREAD

**Issue by j-schwartz** [rachelproject/eos-justice#13] opened 2017-04-29 17:21 UTC
this may be my particular setup, but it should be a universal error, currently videos are pulled into a second 'content' subdirectory inside the primary content subdirectory.  Videos should be in kalite/content/. not kalite/content/content/.

**Comment by quarckster** [comment] 2017-04-29 17:22
Duplicate of #12

**Closed as completed by quarckster** 2017-04-29 17:22 UTC
